name: Build and Release
on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21' # Adjust to your desired Go version

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and Release
        env:
          NAME: connect_jxyy_network # Adjust the project name
          BINDIR: bin
        run: |
          make releases

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }} # Use a GitHub Personal Access Token
