name: Multi-Arch Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: [1.16]  # 可以根据需要更改Go版本
        os: [windows-latest, ubuntu-latest, macos-latest]  # 不同操作系统
        arch: [amd64, arm64, arm, mips, mips64, ppc64le, s390x, wasm]  # 不同架构

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o myapp_${{ matrix.os }}_${{ matrix.arch }}

      - name: Archive Artifacts
        run: tar -czf myapp_${{ matrix.os }}_${{ matrix.arch }}.tar.gz myapp_${{ matrix.os }}_${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp_${{ matrix.os }}_${{ matrix.arch }}-release
          path: myapp_${{ matrix.os }}_${{ matrix.arch }}.tar.gz
